Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#MkCodeBox("src/popcnt_bb.S", "gas", "<b>CODE: asm - Our First assembly program - Playing with popcnt", "200%", "640px")
#FileCodeBox("src/hello_bb.c", "C", "<b>CODE: C - Hello World")
display(Markdown(FileCodeBox(
    file="src/popcnt_bb.S", 
    lang="gas", 
    title="<b>CODE: asm - Our First assembly program - Playing with popcnt",
    h="600px", 
    w="640px"
)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [7][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m#MkCodeBox("src/popcnt_bb.S", "gas", "<b>CODE: asm - Our First assembly program - Playing with popcnt", "200%", "640px")[39;00m
[1;32m      2[0m [38;5;66;03m#FileCodeBox("src/hello_bb.c", "C", "<b>CODE: C - Hello World")[39;00m
[0;32m----> 3[0m display(Markdown([43mFileCodeBox[49m[43m([49m
[1;32m      4[0m [43m    [49m[43mfile[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43msrc/popcnt_bb.S[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      5[0m [43m    [49m[43mlang[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mgas[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      6[0m [43m    [49m[43mtitle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m<b>CODE: asm - Our First assembly program - Playing with popcnt[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      7[0m [43m    [49m[43mh[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m600px[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m
[1;32m      8[0m [43m    [49m[43mw[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m640px[39;49m[38;5;124;43m"[39;49m
[1;32m      9[0m [43m)[49m))

File [0;32m~/UnderTheCovers/content/python/common.py:66[0m, in [0;36mFileCodeBox[0;34m(file, lang, number, **kwargs)[0m
[1;32m     64[0m [38;5;28;01mdef[39;00m [38;5;21mFileCodeBox[39m(file, lang, number[38;5;241m=[39m[38;5;28;01mFalse[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     65[0m     [38;5;66;03m#open text file in read mode[39;00m
[0;32m---> 66[0m     text_file [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfile[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m     67[0m     [38;5;66;03m#read whole file to a string[39;00m
[1;32m     68[0m     data [38;5;241m=[39m text_file[38;5;241m.[39mread()

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'src/popcnt_bb.S'
FileNotFoundError: [Errno 2] No such file or directory: 'src/popcnt_bb.S'

